use_frameworks!
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
]
pod 'RNFS', :path => '../node_modules/react-native-fs'
